name: quality-check
description: check lint

runs:
  using: 'composite'
  steps:
    - name: Lint code
      run: pnpm run lint
      shell: bash

    - name: run unit tests
      run: pnpm run test
      shell: bash