name: Deploy to Netlify

on:
  workflow_dispatch:

jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/workflows/actions/setup-node

      - name: Build app
        run: pnpm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify (Production)
        run: netlify deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}